version: '3.8'

services:
  # Base de datos
  db:
    image: pgvector/pgvector:pg16
    restart: always
    container_name: mfnews_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: contraseña123
      POSTGRES_DB: mfnews  # La base se llama "mfnews"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend NestJS
  backend:
    build: .
    container_name: mfnews_backend
    ports:
      - '3000:3000'
    environment:
   
      DATABASE_URL: "postgresql://admin:contraseña123@db:5432/mfnews?schema=public"
    depends_on:
      # ### CORREGIDO 3: Debe coincidir con el nombre del servicio de arriba
      - db

  # Frontend (React)
  frontend:
    build:
      context: ../mfnews-frontend
      dockerfile: Dockerfile
    container_name: mfnews_frontend
    ports:
      - '5173:5173'
    volumes:
      - ../mfnews-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api

volumes:
  postgres_data: