version: '3.8'

services:
  # 1. Base de datos
  db:
    image: postgres:16
    restart: always
    container_name: mfnews_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: contraseña123
      POSTGRES_DB: mfnews
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Backend NestJS (Fíjate que está indentado debajo de services)
  backend:
    build: .
    container_name: mfnews_backend
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://admin:contraseña123@db:5432/mfnews?schema=public'
    depends_on:
      - db
    # Configuración para Hot Reload (Desarrollo)
    volumes:
      - .:/app # Sincroniza tu carpeta actual con /app en el contenedor
      - /app/node_modules # Protege la carpeta node_modules interna
    command: npm run start:dev # Sobreescribe el comando de producción

  # 3. Frontend React
  frontend:
    build:
      context: ../mfnews-frontend
      dockerfile: Dockerfile
    container_name: mfnews_frontend
    ports:
      - '5173:5173'
    volumes:
      - ../mfnews-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000/api

volumes:
  postgres_data:
